FROM python:3.10.13-slim as builder

ENV APP_HOME /app
WORKDIR $APP_HOME
COPY linebot.py ./app.py
COPY requirements.txt ./
COPY run_line_beta.py ./
COPY agents ./agents

RUN pip install --no-cache-dir --upgrade pip && pip install --no-cache-dir -r requirements.txt

CMD exec gunicorn --bind :$PORT --workers 1 --threads 8 --timeout 0 app:app